### ISSUE TITLE
"_this2.setState is not a function."

### ISSUE THREAD

**Issue by sens2010** [marcshilling/react-native-image-picker#109]
I'm a new for rect-native, but I even can't run the example which is given. It get the error as title when it run the code:
`this.setState({
          avatarSource: source
        });`
and when I add the invoker into my own project, it give another warning and doesn't work properly:
Attempt to present <UIAlertController: 0x7ff8ad99e9d0> on <UIImagePickerController: 0x7ff8c49f2e00> whose view is not in the window hierarchy!
Is there some wrong with my environment?

**Comment by yfuks** [comment]
```
_this2.setState is not a function
```

mean that you don't have the react class context in your function

for exemple on the onPress you can do like :
```javascript
onPress={() => this.myFunction()}
```

To bind your react class context into your function

**Comment by marcshilling** [comment]
Not an issue with this library

**Comment by MilosHavel** [comment]
I am newbie of React Native developer, I have used this lib on my project. 
And I could not go ahead since I met this issue.
I could not set the image with lib image, it said "_this2.setState is not a funciton."
Could you help me?
![screen shot 2017-06-29 at 05 49 58](https://user-images.githubusercontent.com/18087087/27670758-44365560-5c8f-11e7-9fc0-d8229cffd2a6.png)

**Comment by Julia-Lavrova** [comment]
try use `() => {}` 

```
  showActionSheet = () => {
    {your code}
  } 
```

**Comment by atulaccedo** [comment]
I faced a similar problem and noticed that I was using `this.state.setState()` method instead of `this.setState()`. Just sharing in case it helps anybody.
