### ISSUE TITLE
Disable Photos access from Privacy settings crash the example app.

### ISSUE THREAD

**Issue by 5amfung** [marcshilling/react-native-image-picker#156]
After running the example and granting Photos access, go to Settings > Privacy > Photos, and disable the access.  The app crashes immediately from the simulator.  I haven't tested it on a real device.  But I think if it crashes in the simulator, it'll likely crash on real device.

**Comment by marcshilling** [comment]
Yep, just tested and you're right, it does crash. However, upon a subsequent launch, it does not crash and displays the friendly "This app does not have access to your photos" screen when you try to view your photo library.

This is a rare edge case and since the app technically works with the disabled permissions, I don't particularly care that it crashes if you change permissions while using the app. If you know of a way to prevent the crash and want to submit a PR, I'll accept. Thanks!
