### ISSUE TITLE
iOS: Unable to pan image taken with camera

### ISSUE THREAD

**Issue by nlively** [marcshilling/react-native-image-picker#159]
When I snap a photo (vs getting it from my photo library) and then see the screen where I can pan/crop the image to the given rectangle, I am unable to pan my photo.

When I take it from the photo library, I can pan the photo without any problem.

Using 0.18.3

**Comment by marcshilling** [comment]
I can't reproduce. I just took a photo and was able to pan/zoom the photo in the subsequent edit mode. I specified `allowsEditing: true` in my options.

**Comment by spicylobster** [comment]
I meet the same problem. when I take a photo I cannot move the crop box. It seems the photo is treated like a 1:1 one.  But I can zoom it. when I zoom in, I can move the crop box. when I user photo from the library everything is ok

I'm using 0.18.5

**Comment by rgoldiez** [comment]
+1

When I take a picture w/ the camera, I can zoom, but I can't pan the full range of the image.

**Comment by marcshilling** [comment]
Guys, I don't know what to tell you here...everything is working correctly as far as I can tell.

@spicylobster "when I zoom in, I can move the crop box"...yeah...this makes sense because your iPhone photos in portrait are the width of the screen. Of course you can't pan when the photo is already displayed at full width. When you zoom in, the photo is larger than the width of the screen, allowing you to pan.

Am I just totally missing something here?

**Comment by nlively** [comment]
The photo preview box, because it is square, is smaller than the height of
the screen.  So if I want to reposition the photo within the square, I am
unable to.  I'm forced to have the square in the exact center of my photo.

On Tue, Apr 19, 2016 at 7:23 AM, Marc Shilling <notifications@github.com>
wrote:

> Guys, I don't know what to tell you here...everything is working correctly
> as far as I can tell.
>
> @spicylobster <https://github.com/spicylobster> "when I zoom in, I can
> move the crop box"...yeah...this makes sense because your iPhone photos in
> portrait are the width of the screen. Of course you can't pan when the
> photo is already displayed at full width. When you zoom in, the photo is
> larger than the width of the screen, allowing you to pan.
>
> Am I just totally missing something here?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/marcshilling/react-native-image-picker/issues/159#issuecomment-211943348>
>



-- 
Noah Lively
Founder/CEO

*KoreMedia Productions*
*Website solutions, mobile apps and more since 2001*

Website: http://www.koremedia.net
Email: noah.lively@koremedia.net
Office: (916) 776-6249
Toll-Free: (855) 336-9900
Cell: (916) 220-4715
Skype: noahlively

*"Do things that have never been done before."*

**Comment by rgoldiez** [comment]
Same problem here.

**Comment by marcshilling** [comment]
Ok. I understand now.

Apparently, this is a bug in iOS. [See here](http://stackoverflow.com/questions/20000273/uiimagepickercontroller-with-allowsediting-doesnt-allow-panning-to-crop)

The top answer [here](http://stackoverflow.com/questions/9041732/set-dimensions-for-uiimagepickercontroller-move-and-scale-cropbox) has a solution for accomplishing this without the built in `allowsEditing` option of `UIImagePickerController`. I welcome anyone to attempt this change and submit a PR. Since I don't have this immediate need in my apps, I won't be working on it.

**Comment by knowbody** [comment]
+1

**Comment by NaturalLam** [comment]
Unfortunately that is the native behavior too

**Comment by nica0012** [comment]
This is still an issue... Been hoping this would get resolved over 2019 but images taken with the camera are not able to pan to the top (bottom stuck under pan area). Images from the picker work fine.

The current IOS camera crops fine, maybe there needs to be an update?
