### ISSUE TITLE
Add flag for Android to copy to always copy to temp / caches directory

### ISSUE THREAD

**Issue by corymsmith** [marcshilling/react-native-image-picker#206]
The use case I have is that a user can take a photo or choose one from Photos or the Gallery. The image path / URI's are cached and saved along with some other data to be synced later. The issue is that a user could remove that image from their gallery and then it wouldn't be there to sync later on. I need to have the files always stored in the caches directory so that removing the file from the Gallery or Photos doesn't affect the file stored. 

I'm currently copying the file manually and getting a new URI as well to ensure theres no issues if a file is moved.

Would you accept a PR for a flag that would copy an image even when picked from gallery?

**Comment by yfuks** [comment]
Hi @corymsmith 

Saving photo into a caches directory ??? (Obviously it's a cache directory so you don't want to save anything that you want to access later in it)

##### Android docs about cache directory :

> When the device is low on internal storage space, Android may delete these cache files to recover space. However, you should not rely on the system to clean up these files for you. You should always maintain the cache files yourself and stay within a reasonable limit of space consumed, such as 1MB. When the user uninstalls your application, these files are removed.

I hope you mean saving into the [internal storage](https://developer.android.com/guide/topics/data/data-storage.html#filesInternal)


A really simple way to answer your problem is probably to check if the file exist when you want to use it (saving big content like images in the internal storage are usually a bad idea)

But if you want to **PR** a way to save images in the [internal storage](https://developer.android.com/guide/topics/data/data-storage.html#filesInternal) or just simply [app-private](https://developer.android.com/guide/topics/data/data-storage.html#AccessingExtFiles) files, you are welcome.
