### ISSUE TITLE
Question: analyze chosen image BEFORE going to resize screen?

### ISSUE THREAD

**Issue by andrewheppner** [marcshilling/react-native-image-picker#208]
Hello,
I was wondering if there was a way of accessing the data for the chosen image in the image picker BEFORE the user is sent to the image editing screen. I would like to limit user selections to images with a certain dimension. 

Thanks very much.

**Comment by yfuks** [comment]
Hi @andrewheppner,

I can only talk about **Android** and i can say that is possible but i will not do it .To access the image data before you crop it you need to split the *Activity* (Currently one activity pick and crop). So it will give you one *Activity* for the pick and one for the crop. It's not a great thing to do since the *crop Activity* is badly supported in **Android**.

Like said in #177 maybe one day *hopefully* there will be a custom *crop Activity* in this module that will solve this kind of problems

**Comment by andrewheppner** [comment]
Thanks @yfuks! Would it be possible to point out around which lines in the source code this activity is found( android and ios?)? I took a look for a while, but couldn't quite find it. 

Thanks a lot for your help. 
Andrew

**Comment by marcshilling** [comment]
I don't believe this is possible on iOS. You have to set `allowsEditing` on `UIImagePickerController` before displaying it...and there's no callback until the entire process is complete. Might be possible with [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) since they use 3rd party libraries and perform the 2 steps separately. I would open up an issue or fork that repo if you need this functionality.

**Comment by andrewheppner** [comment]
Thanks a lot for the help. Cheers!
