### ISSUE TITLE
Can't resize the image on Android

### ISSUE THREAD

**Issue by eulphean** [marcshilling/react-native-image-picker#230]
I'm seeing a red screen on Android after I select a file from the camera roll. 

The error is 'Can't resize the image' and I see it when I give it an allowsEditing = true flag.

**Comment by yfuks** [comment]
**On some devices the crop is not supported** and since there is 1000 implementation of it it not allways return an error in the code (i see the case in some chinese phones) so we end up in further code with an empty file that can't be resized.

I recommend you to not use ```allowsEditing: true``` if you are not sure about the type of phone that will use your app

**Comment by marcshilling** [comment]
@yfuks man, I'm starting to think we should just remove the `allowsEditing` functionality on Android. I'm sick of dealing with all these issues...

**Comment by limulidae** [comment]
+1
