### ISSUE TITLE
[Android] After compiling release APK, app starts restarting when taking a picture

### ISSUE THREAD

**Issue by timoncp** [marcshilling/react-native-image-picker#316]
Hi guys, haven't had an issue with the library until now while running the debug version on the device.
But after testing out the compiled apk (./gradlew installRelease or assembleRelease) I've noticed that the app is restarting after taking a picture, pressing OK, and trying to go back into RN.

Steps to reproduce:
- call showImagePicker()
- choose from camera
- take photo
- press OK

I have already checked out #244 and #190, the portrait fix didn't work for me, and I don't understand the ways of android java yet to try the fix [here](http://stackoverflow.com/questions/10176550/android-system-stops-application-when-launching-media-intent/10266261#10266261). I'm guessing you have to modify the way RN works internally?

Thank you.

Note: I have noticed this on both RN 0.33 and RN 0.25, with both the latest version of Image Picker and an older one. It only happens after compiling the project to APK and running it on the phone.

**Comment by marcshilling** [comment]
I've never had this happen before. Please try to investigate more yourself and submit a PR if you can.

**Comment by marcshilling** [comment]
Can you try `v0.22.8` on npm?

**Comment by timoncp** [comment]
Will give it a try soon. 

It seems like the issue is related to RN instance management within the Android code, since opening the camera creates an instance of itself. It happens in react-native-image-crop-picker as well. When it returns to RN it returns -1, when it was expecting something else. I couldn't really pinpoint the location in logcat where this was mentioned since I don't know how to filter it properly...

What I did for now was integrate a camera within the context of RN, which seems to work ok. I lost all the features from the default android camera app/component though.

**Comment by timoncp** [comment]
So, I tried _v0.22.9_ and compiled to APK. Works like a charm again. Good job :+1:

I think [this commit](https://github.com/marcshilling/react-native-image-picker/commit/4d6f5c2a778d65137db9969d7d51d29af7ec0ae8) solved it.

**Comment by GopiKrishna10** [comment]
hi Guys,
i am still facing a issue when I take the picture and press OK button the app get restarted.in all mobiles like redmi note4 and moto g2. am trying to resolve from one day. am not able to solve this can u please help me thanks in advance @marcshilling 

i update the version react-native-image-picker from 0.26.3 to 0.22.9. app getting like "unfortunately app has stopped" showing pop up like this.

config

"react-native": "^0.42.3",
"react-native-image-picker": "0.22.9"
db is firebase

options are

var options = {
title: 'Select Avatar',
quality: 0.6,
storageOptions: {
skipBackup: true,
path: 'images'
}
};

**Comment by SudoPlz** [comment]
Actually that issue is a duplicate of https://github.com/react-community/react-native-image-picker/issues/732

**Comment by nathanfoster048-lab** [comment]
This sounds more like the Android activity being killed and recreated while the camera is open, rather than an issue with taking the photo itself.

Since it only happens with the release APK, I would check the Android logcat output immediately after pressing OK. Look for `ActivityManager`, `ReactNative`, or an `OutOfMemoryError` message. That should tell you whether Android is killing the RN activity or if the image picker is causing a crash.

Also worth checking the camera/image size. A large photo can use quite a bit of memory, and release builds can sometimes expose problems that don't show up in debug.

If logcat shows the activity being recreated without a real crash, then saving/restoring the activity state around the camera intent would be the next thing I'd investigate.
