### ISSUE TITLE
[iOS] Cancel button title null produces error

### ISSUE THREAD

**Issue by tomazahlin** [marcshilling/react-native-image-picker#357]
Hello, I want to hide the cancel button on iOS, because cancel also happens when clicking in the background.

This is the options which I pass to ImagePicker:

const options = {
        mediaType: 'photo',
        quality: 0.8,
        title: null,
        takePhotoButtonTitle: 'Foto aufnehmen',
        chooseFromLibraryButtonTitle: 'Aus der Galerie auswählen',
        cancelButtonTitle: null, // null means no button
        storageOptions: {
            skipBackup: true,
            path: 'images'
        }
    };

But with cancelButtonTitle set to null, I get the following error:

![simulator screen shot 18 oct 2016 11 48 16](https://cloud.githubusercontent.com/assets/5858023/19472813/14b7e85e-9529-11e6-8dc8-5fc9e2fd647b.png)

If I set cancelButtonTitle to '' (empty string), the button is still there, blank without text. Can you help?

The documentation says that this is for Android only, but why? Could that not be added for iOS too? Or maybe you should make a '-' instead of OK in the ios/android comparison table.

**Comment by marcshilling** [comment]
This functionality was only added for Android. If I have some time today I will add it to iOS.

**Comment by marcshilling** [comment]
@tomazahlin I think you actually may be mistaken when you say "cancel also happens when clicking in the background". I was implementing this change and realized that without the "Cancel" button and corresponding action, you cannot dismiss the `UIAlertController`. It would be possible to do this in a hacky way by adding a tap-handling view behind the alert controller, but that seems like a lot of unnecessary work. We're gonna stick with the native iOS behavior here - just show a cancel button.

**Comment by yfuks** [comment]
```javascript
cancelButtonTitle: (Platform.OS === 'ios') ? 'Cancel' : null
```

**Comment by tomazahlin** [comment]
@marcshilling Alright. But in my scenario, in iOS I can click in the transparent background and it dismisses the modal, so I don't need the cancel button. It is not the same in your case?

**Comment by marcshilling** [comment]
@tomazahlin yes I realize that. What I'm saying is the only reason that it works is because the cancel button is present. If I remove the cancel button, it ALSO removes the functionality of being able to "click in the transparent background and it dismisses the modal". I just tested it. More insight [here](http://stackoverflow.com/questions/30075832/how-to-dismiss-uialertcontroller-when-tap-outside-the-uialertcontroller).

**Comment by tomazahlin** [comment]
@marcshilling Okay, all clear. Thanks!
