### ISSUE TITLE
[Android] Solution for FileUriExposedException in SDK 24

### ISSUE THREAD

**Issue by tijs** [marcshilling/react-native-image-picker#376]
Starting with Android SDK 24 it is no longer allowed to expose the file: path. Instead it's recommended to use the content: URI. More info here:

https://developer.android.com/reference/android/os/FileUriExposedException.html

For now it's solved by not targeting SDK 24 but at some point this will not be an option anymore :)

**Comment by marcshilling** [comment]
@yfuks can we do something about this? Maybe we can remove `path` from the Android response?

**Comment by yfuks** [comment]
I have to look some documentation. I don't know what is the difference between `content://uri` and `file://uri`. And how to specifically get the `content://uri`
Not sure that simply removing the `path` will fix this..

**Comment by thorbenprimke** [comment]
Downgrade to targetSDK 23 fixes it temporarily. 

https://developer.android.com/training/camera/photobasics.html
^^^ Outlines how to work with the Camera and `content://`

I'll try to get a PR out this weekend.

**Comment by camlahoud** [comment]
You can switch to using the FileProvider class as outlined in [https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en) for example.

But I would recommend adding a condition based on the android version instead of following their advice to just change from Uri.fromFile to using FileProvider. Something like:
```
File imageFile = createNewFile();
      if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
        mCameraCaptureURI = Uri.fromFile(imageFile);
      } else {
        cameraIntent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
        mCameraCaptureURI = FileProvider.getUriForFile(mReactContext,
                mReactContext.getApplicationContext().getPackageName() + ".provider",
                imageFile);
      }
```

**Comment by cooperka** [comment]
Thanks for the link @thorbenprimke. Were you ever able to work on a PR?

**Comment by skv-headless** [comment]
Will appreciate any feedback.
