### ISSUE TITLE
Disable 'Compressing Video'

### ISSUE THREAD

**Issue by StevePotter** [marcshilling/react-native-image-picker#416]
Hi, we are using your awesome plugin for selecting videos to upload.  In iOS, we're uploading the response.origURL property that starts with "assets-library:".  We do this to avoid compressing the video twice, as we have mandatory video transcoding after upload.  When the user selects a video, it runs for a while "Compressing Video", resulting in the response.uri property from the picker callback.  Since we aren't using the compressed file, can that step be skipped?  

I looked into the .m file and don't see that option in the UIImagePickerController documentation.  videoQuality is required and there is nothing I saw that will cause it to skip the compression.  Do you know if this is possible?  If so, any information would be helpful.  I'll happily contribute a PR if it's possible in iOS.  Thanks!

**Comment by marcshilling** [comment]
According to [this Stack Overflow post](http://stackoverflow.com/a/5893066/3178793), that is built-in iOS functionality and there is no way to disable it. 

Is that what you're experiencing?

**Comment by slickdev** [comment]
Going back to this issue - now in iOS 11 it seems it's possible to stop the video compression from happening: https://stackoverflow.com/questions/20190485/how-to-avoid-compression-after-selecting-video-from-uiimagepickercontroller-in-i

Do you think you can implement this into the library so that we can disable the compression? In my case the compression process is taking forever and I don't want the videos compressed anyway.

Thanks in advance
