### ISSUE TITLE
Recommended Way to "Clean Up" Created Images?

### ISSUE THREAD

**Issue by joncursi** [marcshilling/react-native-image-picker#417]
Is there a recommended way to clean up images that are created vis-a-vis this package? I noticed that a bunch of files are getting stuffed into `Documents/images` and I'm trying to figure out the best way to clear that out after the user has completed their task that generated the image.

<img width="589" alt="screen shot 2016-12-10 at 8 39 23 am" src="https://cloud.githubusercontent.com/assets/4974609/21073702/42de9eee-beb4-11e6-94d5-fefae0b5e736.png">

**Comment by marcshilling** [comment]
Seems like you're providing the `storageOptions` key in your options dictionary. That's what saves the images. If you don't want them saved simply omit that key.

**Comment by joncursi** [comment]
Fantastic, thank you!

**Comment by skr1t** [comment]
I still have two questions about this issue:

1. If you **ARE NOT** using this option, images are stored in a "tmp" folder. When is this folder being emptied? Because I can't find a trigger that does this.

2. If you **ARE** using this option because you want to use the cameraRoll option, you have to provide the clean up service yourself? For example, empty the (specific) folder after the upload to the backend is finished.

Kind regards.

**Comment by filipsuk** [comment]
@skr1t I have the same questions. Did you find some answers? Thx

**Comment by skr1t** [comment]
No, I have no answers to the questions. We opted for the camera roll option, so that users themselves are responsible for the storage management.
So far we haven't received any comments about this.

**Comment by lbelavoir** [comment]
@skr1t apparently there's an issue opened on storage management here #986
