### ISSUE TITLE
Enhancements for streamlining camera/image capture.

### ISSUE THREAD

**Issue by halibut** [marcshilling/react-native-image-picker#423]
**Use case**: Apps that need to capture an image from the camera, and want to remove all but the most basic interaction from the user.

**Platform:** I've only tested on iOS so far.

**Enhancement 1**: Is it possible to launch the camera with the flash mode set to "auto"? Right now, it always launches as "off". Alternatively, if it's not possible to pass as an argument, it would be fine if the setting persisted across launches of the camera. Right now, it is inconvenient for users who are taking a lot of photos and need to change the flash setting every time.

**Enhancement 2**: Is it possible to remove/skip the capture confirmation dialog ("Retake" or "Use Photo") that happens after taking the picture? In my app, I would like to immediately apply some processing to the image once the photo is taken without forcing the user to confirm. The current 2-step process is a (slight) inconvenience for my users who take a lot of photos. 

I know that this is an "image picker" library, so my use case is sort of at the edge of what this was designed for. So if these enhancements aren't something you would consider, feel free to close the issue.

BTW, I know these sound like gripes, but I appreciate the library and the work you have put into it. It's fantastic!

**Comment by marcshilling** [comment]
@halibut these are some valid enhancements, but both things you've described are a part of the built-in iOS functionality of the `UIImagePickerController` that we are using under the hood. One of the things that I am very committed to doing with this library is keeping it as a pure bridge of the native iOS/Android functionality. Otherwise, this repo would spiral out of control trying to cover everyone's use cases because there are a million things that can be done with Photos/Cameras on iOS and Android. 

The image picker functionality provided here is intended to be used for a "Choose Profile Photo" type interaction in an app. You sound like you're building a camera app, and if that's the case this really isn't meant for you. You'll have to dip further down into native code to do things like automatically enabling flash. As for Enhancement 2, you'd pretty much get that for free using anything other than `UIImagePickerController`
