### ISSUE TITLE
width and height of the image

### ISSUE THREAD

**Issue by pgmemk** [marcshilling/react-native-image-picker#43]
Thank you so much for this module AGAIN :)

It would be great to be able to get the original image dimensions. 
I am using the component that displays image in full screen mode and it would be great to display it using the original proportions

**Comment by marcshilling** [comment]
I'm going to implement this now...are you specifying the `maxWidth` and `maxHeight` options in your use case? I'd love to just return `width` and `height` in the response. So if you supplied `maxWidth` or `maxHeight`, those values would be returned, otherwise it would return the original dimensions. Does that sound good or do you want the original dimensions even when specifying `maxWidth` and `maxHeight`?

**Comment by pgmemk** [comment]
Great, thank you

I don't specify maxWidth and maxHeight I really need just the original
dimensions
ᐧ

On Tue, Oct 27, 2015 at 2:33 PM, Marc Shilling <notifications@github.com>
wrote:

> I'm going to implement this now...are you specifying the maxWidth and
> maxHeight options in your use case? I'd love to just return width and
> height in the response. So if you supplied maxWidth or maxHeight, those
> values would be returned, otherwise it would return the original
> dimensions. Does that sound good or do you want the original dimensions
> even when specifying maxWidth and maxHeight?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcshilling/react-native-image-picker/issues/43#issuecomment-151519257>
> .
>



-- 
Ellen Katsnelson
Lead Developer

**Comment by marcshilling** [comment]
This is live in version 0.9!
