### ISSUE TITLE
Get image details

### ISSUE THREAD

**Issue by eyaleizenberg** [marcshilling/react-native-image-picker#46]
Hi,
When I pick an image from the camera roll the response returns:
../BDBBE016-79D4-4950-82F8-A3E7B97634F9.jpg

Is there a way to get the real file name and it's size?

Thanks!

**Comment by marcshilling** [comment]
I just pushed an update this morning that adds width/height to the response. Let me look into getting the original file name. If I returned the actual path of the image on device, would that be sufficient?

**Comment by eyaleizenberg** [comment]
Actual path which shows the real file name would be great but if you could
get the file size as well it would be awesome! I noticed the dimensions,
that's cool.

**Comment by levic92** [comment]
Technically "../BDBBE016-79D4-4950-82F8-A3E7B97634F9.jpg" is the real file name of the image you are receiving from this plugin - [see here](https://github.com/marcshilling/react-native-image-picker/blob/master/UIImagePickerManager/UIImagePickerManager.m#L190-L191)

If you want the original name from the camera roll that is possible ([example](http://stackoverflow.com/questions/4314405/how-can-i-get-the-name-of-image-picked-through-photo-library-in-iphone)), but I think you will receive something like "IMG_0001.JPG". Just curious in what benefit this provides?

**Comment by marcshilling** [comment]
Yup, @levic92 is correct. It's definitely possible but I'm also curious of the benefit. Also should be noted that if you choose "Take Photo", it's always going to be the long UUID file name. I could only return the "real" file name for photos selected from the library.

**Comment by eyaleizenberg** [comment]
Files can also be something.png that you've downloaded before hand.  If you are picking a picture from the camera roll it's better to get img_01.jpg rather than a bunch of random letters and numbers. The file size is really important in my opinion.  For example in my app I upload a picture to s3. I don't want a user to try and upload a big file if I know before hand that the file is way too big. I also need the file size for information purposes for the users. 

Thanks.

**Comment by eyaleizenberg** [comment]
@levic92 Any chance to make a react native version of that? I am clueless when it comes to objective c

**Comment by levic92** [comment]
I would have to disagree and say that a UUID file name is much better, this way you never run into conflicting file names.

As for the size of the image returned, I believe ```data.length``` could be called to get the bytes - [see here](https://github.com/marcshilling/react-native-image-picker/blob/master/UIImagePickerManager/UIImagePickerManager.m#L244). 

@eyaleizenberg There is also the quality option to set the compression.

@eyaleizenberg For any of these changes, the objective-c code would need to be implemented in this project and then values from objective-c are passed back in the response to react native.

**Comment by eyaleizenberg** [comment]
@levic92 @marcshilling So maybe a choice can be given to get a uuid or a filename?

**Comment by levic92** [comment]
@eyaleizenberg I'm talking about calling length on NSData in the objective-c code.

**Comment by eyaleizenberg** [comment]
So, any chance to make this happen :wink:  ?

**Comment by marcshilling** [comment]
I don't plan on incorporating this functionality in the core library simply because I believe you have a very specialized use case. However, I can definitely help you out. Why don't you fork my library, and I can make the changes and submit a pull request to your fork.

**Comment by eyaleizenberg** [comment]
@marcshilling There you go. https://github.com/eyaleizenberg/react-native-image-picker

Thanks a lot!

**Comment by marcshilling** [comment]
@eyaleizenberg forgot I can't re-fork a fork of mine...haha...anyway I did the changes. Can you just add me as a collaborator so I can push straight to it?

**Comment by eyaleizenberg** [comment]
@marcshilling just added you.  Thanks!

**Comment by marcshilling** [comment]
@eyaleizenberg OK, pushed. Give it a try and let me know if that's what you are looking for. The image is now saved as its original file name. The only exception to this is if you TAKE a photo, it will still be a UUID filename because the photo is obviously not saved in your photo library. The response also returns `bytes` now.

**Comment by eyaleizenberg** [comment]
@marcshilling For use an existing image it worked great! Thank you so much! However when I tried to take a picture I got this error: "Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates."

Any clue?

Another question, if I added:
```
storageOptions: {
    path: 'images'
  }
```

Doesn't it mean that the picture I will take will end up in the camera roll and then it will have a normal path? Meaning I could get the image_006.jpg path rather than a token? If yes, I would really appreciate it if that could be added as well.

Thank you so much!

**Comment by marcshilling** [comment]
@eyaleizenberg I get that error printed to the console as well, but the app still functions fine and displays the photo I took. Is this not what you are experiencing? The consensus here (http://stackoverflow.com/questions/25884801/ios-8-snapshotting-a-view-that-has-not-been-rendered-results-in-an-empty-snapsho) is that it's an iOS bug.

The `storageOptions` key simply stores the photo in the permanent Documents directory for your app rather than a temporary directory that will be destroyed later. The issue with returning the ACTUAL path of the photo is that when you TAKE a photo rather than choosing one from the library, it will not have an actual path because the photo has not been saved yet. That's why we save it to either a temp or Documents directory. It seems like you are asking to have the photo saved in the user's camera roll and then have that path returned...that functionality is extending far beyond the goals of my library and I don't have time to work on that. This is an image-picker not an image-saver.

I would recommend you dive into the code and attempt it yourself. I believe the `ALAssetsLibrary` accomplishes what you need.

**Comment by eyaleizenberg** [comment]
@marcshilling Thanks for all your help!

**Comment by eyaleizenberg** [comment]
If anybody is interested, I ended up using `CameraRoll.saveImageWithTag` to save the picture taken.
